---
- name: Configure Network Adapters on Backend_Gateway VM
  hosts: 172.28.4.44 # Replace with the hostname or IP address of your Backend Gateway
  become: yes
  remote_user: ammar
  tasks:
    - name: Install isc-dhcp-relay package
      apt:
        name: isc-dhcp-relay
        state: present

    - name: Configure DHCP relay agent
      template:
        src: isc-dhcp-relay  # Replace with your template file path
        dest: /etc/default/isc-dhcp-relay
      notify:
        - restart DHCP Relay

  handlers:
    - name: restart DHCP Relay
      service:
        name: isc-dhcp-relay
        state: restarted
