---
- name: Configure Network Adapters on Backend_Gateway VM
  hosts: DB_Server01 # Replace with the hostname or IP address of your Backend Gateway
  become: yes
  remote_user: root
  vars:
    ansible_python_interpreter: /home/ammar01/Desktop/Ansiblee/Stage3/DB_LAN/MariaDB/myenvv/bin/python3.11
  tasks:

    - name: Start MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes


    - name: Create a new database
      mysql_db:
        name: TestDB
        login_user: root  # Specify the root user here
        login_password: hardtoguess1  # Specify the root user's password here
      when: inventory_hostname in groups['DB_Server01']

  tags:
    - mariadb
    - postgresql
    - ssh