---
- name: Configure Network Adapters on Backend_Gateway VM
  hosts: 120.20.10.239 # Replace with the hostname or IP address of your Backend Gateway
  become: yes
  remote_user: ammar
  tasks:

    - name: Update package cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Apache HTTP Server
      apt:
        name: apache2
        state: present
        
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present
      become: yes

    - name: Start Apache HTTP Server
      service:
        name: apache2
        state: started
        enabled: yes
        

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      become: yes

    - name: Restart HAProxy service
      service:
        name: haproxy
        state: restarted
      become: yes

    - name: Allow HAProxy traffic (port 80)
      ufw:
        rule: allow
        port: 8080
        proto: tcp
      become: yes

    - name: Enable the UFW firewall
      ufw:
        state: enabled

  tags:
    - load_balancer
