---
- name: Configure Network Adapters on Backend_Gateway VM
  hosts: 115.20.2.249  # Replace with the hostname or IP address of your Backend Gateway
  become: yes
  remote_user: ammar
  tasks:

    - name: Update package cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Apache web server
      apt:
        name: apache2
        state: present
      become: yes

    - name: Start Apache service
      service:
        name: apache2
        state: started
      become: yes

    - name: Install PHP and modules
      apt:
        name: "{{ item }}"
        state: present
      become: yes
      with_items:
        - php
        - libapache2-mod-php
        - php-mysql  # If you need MySQL support
        - php-curl   # If you need cURL support
        - php-gd     # If you need GD support

    - name: Allow SSH (port 22) in UFW
      ufw:
        rule: allow
        port: 22
        proto: tcp
        state: enabled
      become: yes
    - name: Restart Apache to apply PHP changes
      service:
        name: apache2
        state: restarted
      become: yes

    - name: Allow incoming HTTP traffic (port 80)
      ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Enable the UFW firewall
      ufw:
        state: enabled

  tags:
    - webserver
