---
- name: Setup Node.js Application
  hosts:  app_servers 
  remote_user: root
  become: yes

  tasks:

    - name: Enable Firewalld on boot
      service:
        name: firewalld
        enabled: yes

    - name: Open multiple ports in firewall
      firewalld:
        zone: public
        port: "{{ item }}/tcp"
        state: enabled
        permanent: yes
      loop:
        - 66
        - 67
        - 22
        - 21
        - 25
        - 443
        - 80
        - 3300
        - 3306

    - name: Open the same ports for UDP
      firewalld:
        zone: public
        port: "{{ item }}/udp"
        state: enabled
        permanent: yes
      loop:
        - 66
        - 67
        - 22
        - 21
        - 25
        - 443
        - 80
        - 3300
        - 3306
        
    - name: Start the Firewalld service
      service:
        name: firewalld
        state: started
        
    - name: Reload Firewall
      command: firewall-cmd --reload